#tk_place.py
import tkinter as tk
win = tk.Tk() 
win.geometry("200x100")
but1 = tk.Button(win, text="NW") 
but1.place(relx=0, anchor=tk.NW) 
but2 = tk.Button(win, text="NE") 
but2.place(relx=1, anchor=tk.NE) 
but3 = tk.Button(win, text="SW") 
but3.place(relx=0, rely=1, anchor=tk.SW) 
but4 = tk.Button(win, text="SE") 
but4.place(relx=1, rely=1, anchor=tk.SE) 
but5 = tk.Button(win, text="CENTER") 
but5.place(relx=0.5, rely=0.5, anchor=tk.CENTER)
but6 = tk.Button(win, text="E") 
but6.place(relx=1, rely=0.5, anchor=tk.E)
but7 = tk.Button(win, text="W") 
but7.place(relx=0, rely=0.5, anchor=tk.W)
but8 = tk.Button(win, text="S") 
but8.place(relx=0.5, rely=1, anchor=tk.S)
but9 = tk.Button(win, text="N") 
but9.place(relx=0.5, rely=0, anchor=tk.N)
win.mainloop()
